dependencies:
  - name: inventory-management-svc-oc43-yks
    version: 0.0.5
    repository: >-
      https://artifactory-tools.gsi-dev-ocp43-clu-405282-7ec5d722a0ab3f463fdc90eeb94dbc70-0000.us-east.containers.appdomain.cloud/artifactory/generic-local/dev-yks/
