global:
  ingressSubdomain: gsi-dev-ocp43-clu-751315-7ec5d722a0ab3f463fdc90eeb94dbc70-0000.sjc04.containers.appdomain.cloud
  tlsSecretName: gsi-dev-ocp43-clu-751315-7ec5d722a0ab3f463fdc90eeb94dbc70-0000

inventory-management-svc-ocp43-yks:
  replicaCount: 3
  
  ingress:
    enabled: true
    tlsSecretName: gsi-dev-ocp43-clu-751315-7ec5d722a0ab3f463fdc90eeb94dbc70-0000

